=== elgarcito/solvd-2-block-homework-4/src/main/resources/xsdFiles/labTestReport.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="equipmentForTestModelType">
        <xs:sequence>
            <xs:element name="modelName" type="xs:string"/>
            <xs:element name="modelDescription" type="xs:string"/>
            <xs:element name="releaseDate" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="batchInfoType">
        <xs:sequence>
            <xs:element name="batchNumber" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="employeeType">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="personalId" type="xs:string"/>
            <xs:element name="birthDate" type="xs:date"/>
            <xs:element name="salary" type="xs:double"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="essayModuleType">
        <xs:sequence>
            <xs:element name="moduleDescription" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required"/>
    </xs:complexType>

    <xs:complexType name="labTestReportType">
        <xs:sequence>
            <xs:element name="essayCode" type="xs:string"/>
            <xs:element name="dateOfEssay" type="xs:date"/>
            <xs:element name="essayDescription" type="xs:string"/>
            <xs:element name="equipmentForTestModel" type="equipmentForTestModelType"/>
            <xs:element name="batchInfo" type="batchInfoType"/>
            <xs:element name="employee" type="employeeType"/>
            <xs:element name="essayModule" type="essayModuleType"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:long" use="required" />
    </xs:complexType>

    <xs:element name="labTestReport" type="labTestReportType"/>
</xs:schema>

=== elgarcito/solvd-2-block-homework-4/src/main/resources/xmlFiles/labTestReport.xml
<labTestReport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="../xsdFiles/labTestReport.xsd" id="1">
    <essayCode>EA1</essayCode>
    <dateOfEssay>2023-12-22</dateOfEssay>
    <essayDescription>Big equipment gas compsumption essay</essayDescription>
    <equipmentForTestModel id="1">
        <modelName>model 1</modelName>
        <modelDescription>Big equipment</modelDescription>
        <releaseDate>2023-01-01</releaseDate>
    </equipmentForTestModel>
    <batchInfo id="1">
        <batchNumber>PR1001</batchNumber>
    </batchInfo>
    <employee id="1">
        <firstName>john</firstName>
        <lastName>smith</lastName>
        <personalId>Abc123</personalId>
        <birthDate>2000-12-15</birthDate>
        <salary>1000</salary>
    </employee>
    <essayModule id="1">
        <moduleDescription>Big equipment module</moduleDescription>
    </essayModule>
</labTestReport>
